

RadiusCursorTemplate = MallornGrove
	Texture        = scmallorngrove
	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
	OpacityMax     = 60%
	OpacityThrobTime  = 1000
	Color          = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer = Yes
End

RadiusCursorTemplate = MirkwoodTrap
	Texture        = scnofurther
	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
	OpacityMax     = 60%
	OpacityThrobTime  = 1000
	Color          = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer = Yes
End

RadiusCursorTemplate = WaystoneTeleport
	Texture        = scroadteleport
	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
	OpacityMax     = 60%
	OpacityThrobTime  = 1000
	Color          = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer = Yes
End

RadiusCursorTemplate = Waystone
	Texture        = scelvenkingsroad
	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
	OpacityMax     = 60%
	OpacityThrobTime  = 1000
	Color          = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer = Yes
End